#!/usr/bin/env python3
import os
import sys
import hashlib

# Paths are relative to this script's directory
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # .../TUSS4470_arduino_r4
WWW = os.path.join(ROOT, 'www')
OUT = os.path.join(ROOT, 'embedded_assets.h')

ASSETS = {
    'FRONTEND_HTML': os.path.join(WWW, 'frontend.min.html'),
    'STYLE_CSS': os.path.join(WWW, 'static', 'style.min.css'),
    'JSCOLORMAPS_JS': os.path.join(WWW, 'static', 'js-colormaps.min.js'),
    'SPECTROGRAM_JS_TPL': os.path.join(WWW, 'static', 'spectrogram.min.js'),
}

def pick_delim(content: str, base: str) -> str:
    base = ''.join(c if c.isalnum() else '_' for c in base)[:15]
    if not base:
        base = 'ASSET'
    delim = f"{base}"
    # Ensure the sequence )DELIM" does not appear in content
    while f"){delim}\"" in content:
        delim += '_X'
    return delim


def main():
    # Read all assets
    contents = {}
    for name, path in ASSETS.items():
        if not os.path.isfile(path):
            if os.path.isfile(path.replace('.min.', '.')):
                path = path.replace('.min.', '.')
            else:
                print(f"Error: missing asset {path}", file=sys.stderr)
                sys.exit(1)
        with open(path, 'r', encoding='utf-8') as f:
            contents[name] = f.read()

    # Generate header
    lines = []
    lines.append('// Auto-generated by tools/embed_assets.py. Do not edit manually.')
    lines.append('#pragma once')
    lines.append('#include <Arduino.h>')
    lines.append('')
    for name, text in contents.items():
        delim = pick_delim(text, name)
        lines.append(f'static const char {name}[] PROGMEM = R"{delim}(')
        lines.append(text)
        lines.append(f'){delim}";')
        lines.append('')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"Wrote {OUT}")

if __name__ == '__main__':
    main()
